LobbyServer:
  - BedwarsLobby#1
BungeeMode: Game
Lobby:
  Spawn: 0.5,100,0.5.5,0,0
  Mini: "02G1"
  LootChest: world,8.5,107.5,-12.5,45,0
arena-start-tutorial:
  - §a▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
  - §f                                §l起床战争
  - ''
  - §e§l      保护你的床并破坏敌人的床。通过从资源刷新点获取铁锭，金锭
  - §e§l                绿宝石和钻石来升级，使自身和队伍变得更强。
  - ''
  - §a▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
MySQL:
  url: 127.0.0.1
  port: 3306
  db: LemonBedWars
  username: root
  password: 123456
APIMySQL:
  url: 127.0.0.1
  port: 3306
  db: LemonAPI
  username: root
  password: 123456
