name: LemonBedWars
version: '0.8'
main: cn.lemoncraft.bedwars.BedWars
commands:
  playmenu:
    description: LemonBedwarsCommand
  bedwarsgame:
    description: LemonBedwarsCommand
  shout:
    description: LemonBedwarsCommand
  start:
    description: LemonBedwarsCommand
  rejoin:
    description: LemonBedwarsCommand
  lemonbedwars:
    description: LemonBedwarsCommand
  bedwars:
    description: LemonBedwarsCommand
  bw:
    description: LemonBedwarsCommand